### ISSUE TITLE
mvn clean verify with error "No <dockerHost> given"

### ISSUE THREAD

**Issue by evainga** [mle-enso/sandbox#9]
On my local version of sandbox, mvn clean verify is not finishing successfully. I get a message of a missing docker host (see message on bottom). Running the docker test `sudo docker run hello-world` works though - so my docker should be installed successfully.

My docker version: 17.12.0-ce

Complete maven output:
> INFO] Scanning for projects...
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] Building sandbox 0.0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ sandbox ---
> [INFO] Deleting /home/evagoettert/git/sandbox/target
> [INFO] 
> [INFO] --- spring-boot-maven-plugin:2.0.0.RC1:build-info (generate build info) @ sandbox ---
> [INFO] 
> [INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ sandbox ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 3 resources
> [INFO] Copying 4 resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ sandbox ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 20 source files to /home/evagoettert/git/sandbox/target/classes
> [INFO] 
> [INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ sandbox ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 2 resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ sandbox ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 18 source files to /home/evagoettert/git/sandbox/target/test-classes
> [INFO] 
> [INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ sandbox ---
> [INFO] 
> [INFO] -------------------------------------------------------
> [INFO]  T E S T S
> [INFO] -------------------------------------------------------
> [INFO] Running de.mle.sandbox.logging.MemoryAppenderTest
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.168 s - in de.mle.sandbox.logging.MemoryAppenderTest
> [INFO] Running de.mle.sandbox.RequestRouterTest
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.614 s - in de.mle.sandbox.RequestRouterTest
> [INFO] 
> [INFO] Results:
> [INFO] 
> [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
> [INFO] 
> [INFO] 
> [INFO] --- asciidoctor-maven-plugin:1.5.5:process-asciidoc (generate-docs) @ sandbox ---
> [INFO] sourceDirectory does not exist. Skip processing
> [INFO] 
> [INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ sandbox ---
> [INFO] Building jar: /home/evagoettert/git/sandbox/target/sandbox-0.0.1-SNAPSHOT.jar
> [INFO] 
> [INFO] --- spring-boot-maven-plugin:2.0.0.RC1:repackage (default) @ sandbox ---
> [INFO] 
> [INFO] --- docker-maven-plugin:0.24.0:start (prepare-containers) @ sandbox ---
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 8.386 s
> [INFO] Finished at: 2018-02-19T22:28:53+01:00
> [INFO] Final Memory: 45M/282M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.24.0:start (prepare-containers) on project sandbox: Execution prepare-containers of goal io.fabric8:docker-maven-plugin:0.24.0:start failed: No <dockerHost> given, no DOCKER_HOST environment variable, no read/writable '/var/run/docker.sock' or '//./pipe/docker_engine' and no external provider like Docker machine configured -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
>

**Comment by mle-enso** [comment]
Did you follow the link at the end of the Docker installation steps?
It reads [Post-installation steps for Linux](https://docs.docker.com/install/linux/linux-postinstall/)
This is essential to (let Maven plugins) run docker without root privileges.

**Comment by evainga** [comment]
You're right, this was indeed the problem. But now I have an other error maessage:

> [INFO] DOCKER> [mongo:latest] "mongo": Start container 4da49f7a2948
> [ERROR] DOCKER> Error occurred during container startup, shutting down...
> [ERROR] DOCKER> I/O Error [Unable to start container id [4da49f7a2948] : driver failed programming external connectivity on endpoint nostalgic_wilson (a865d3abc870bf7d32931000e3268fcba64586a8f9c79b558cf9bbe96d1759d0): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use (Internal Server Error: 500)]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 8.644 s
> [INFO] Finished at: 2018-02-19T22:42:35+01:00
>

**Comment by mle-enso** [comment]
Yes and the answer is right in there:
```
listen tcp 0.0.0.0:27017: bind: address already in use
```
So, quit your process that is currently bound to port 27017... surely a MongoDB.

**Comment by evainga** [comment]
yepp killed it and did a docker restart, now it works, thanks!

**Comment by mle-enso** [comment]
Augmented also the read me hints concerning Docker's post-installation steps.
